# Dependencies
markdown:         kramdown
highlighter:      rogue

# Permalinks
permalink:        pretty

# Setup
title:            d0ct0r<br>4r6a
tagline:          "Arga's Github page"
description:      "Contains Arga's mutters and miscellany."
url:              https://d0ct0r4r6a.github.io
baseurl:          /

author:
  name:           'Arga Roh Sahrijal Saragih'
  url:            https://about.me/d0ct0r4r6a

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/d0ct0r4r6a
