# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            d0ct0r4r6a
tagline:          "Arga's Github page"
description:      "Arga's mutters and miscellany."
url:              https://d0ct0r4r6a.github.io
baseurl:          /

author:
  name:           'Arga Roh Sahrijal Saragih'
  url:            https://about.me/d0ct0r4r6a

paginate:         5

# Custom vars
version:          2.1.0

# Twitter
twitter_username: 'd0ct0r4r6a'

# Github
github:
  repo:           https://github.com/d0ct0r4r6a
